version: '3.8'

services:
  server:
    build:
      context: ./server
    ports:
      - "4000:3000"
    depends_on:
      - db

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server

  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
