INSERT INTO categories (category_name, parent_id)
VALUES 
('צילום', null)
('גרפיקה ועיצוב', null)
('ציור ואיור', null)
('תכנות', null)
('וידאו', null)
('מוזיקה', null)
('צילום', null)
('צילום', null)
('צילום', null)
('צילום', null)
('צילום', null)
('צילום', null)
('צילום', null)
('צילום', null)
('צילום', null)
('צילום', null)

